#ifndef INPUT_CONFIG_H_
#define INPUT_CONFIG_H_


#define INPUT_PIN_COUNT_MAX		8


enum _INPUTTYPE
{
	INPUTTYPE_OFF				= 0,
	INPUTTYPE_IN				= 1,
	INPUTTYPE_COUNTER_UP		= 2,
	INPUTTYPE_COUNTER_DOWN		= 4,
	INPUTTYPE_PERIODE			= 8,
	INPUTTYPE_FREQUENCY			= 16,
	INPUTTYPE_FREQ_PERIOD		= 32
};
typedef uint8_t INPUTTYPE;


typedef struct _TUXONO_INPUT_CONFIG
{
	INPUTTYPE PinConfig[INPUT_PIN_COUNT_MAX];
} TUXONO_INPUT_CONFIG;

#endif /* INPUT_CONFIG_H_ */
